package com.self.activity.dao;

import com.self.activity.model.Certification;

public interface CertificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_certification
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_certification
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int insert(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_certification
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int insertSelective(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_certification
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    Certification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_certification
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int updateByPrimaryKeySelective(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_certification
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int updateByPrimaryKey(Certification record);
}