package com.self.activity.dao;

import java.util.List;

import com.self.activity.model.OrgCustomer;
import com.self.activity.model.OrgCustomerKey;
import com.self.activity.vo.QueryOrgCustomerResult;

public interface OrgCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_org_customer
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int deleteByPrimaryKey(OrgCustomerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_org_customer
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int insert(OrgCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_org_customer
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int insertSelective(OrgCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_org_customer
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    OrgCustomer selectByPrimaryKey(OrgCustomerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_org_customer
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int updateByPrimaryKeySelective(OrgCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_org_customer
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int updateByPrimaryKey(OrgCustomer record);
    
    List<QueryOrgCustomerResult> searchBycustId(String custId);
}