package com.self.activity.dao;

import java.util.List;

import com.self.activity.model.Xindex;

public interface XindexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_xindex
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_xindex
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int insert(Xindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_xindex
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int insertSelective(Xindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_xindex
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    Xindex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_xindex
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int updateByPrimaryKeySelective(Xindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_xindex
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    int updateByPrimaryKey(Xindex record);
    
    List<?> searchByCustId(String custId);
}